### PR TITLE
Use the return value from jwt.sign directly

### LINKED ISSUE #74: README example fails with "algorithm 'none' in JWS header not acceptable"
Doing (as far as I can tell) exactly what the README tells me to:

```
$ gem install acme-client
Fetching: securecompare-1.0.0.gem (100%)
Successfully installed securecompare-1.0.0
Fetching: bindata-2.3.1.gem (100%)
Successfully installed bindata-2.3.1
Fetching: url_safe_base64-0.2.2.gem (100%)
Successfully installed url_safe_base64-0.2.2
Fetching: json-jwt-1.6.2.gem (100%)
Successfully installed json-jwt-1.6.2
Fetching: acme-client-0.3.3.gem (100%)
Successfully installed acme-client-0.3.3
5 gems installed
$ irb
>> require 'openssl'
=> true
>> private_key = OpenSSL::PKey::RSA.new(4096)
=> #<OpenSSL::PKey::RSA:0x00000001708fb8>
>> endpoint = 'https://acme-staging.api.letsencrypt.org/'
=> "https://acme-staging.api.letsencrypt.org/"
>> require 'acme-client'
=> true
>> client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options: { request: { open_timeout: 5, timeout: 5 } })
=> #<Acme::Client:0x00000001329230 @connection_options={:request=>{:open_timeout=>5, :timeout=>5}}, @directory_uri=nil, @private_key=#<OpenSSL::PKey::RSA:0x00000001708fb8>, @endpoint="https://acme-staging.api.letsencrypt.org/", @nonces=[], @operation_endpoints={"new-authz"=>"/acme/new-authz", "new-cert"=>"/acme/new-cert", "new-reg"=>"/acme/new-reg", "revoke-cert"=>"/acme/revoke-cert"}>
>> registration = client.register(contact: 'mailto:contact@example.com')
Acme::Client::Error::Malformed: algorithm 'none' in JWS header not acceptable
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:37:in `raise_on_error!'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:27:in `on_complete'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `block in call'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `call'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client.rb:23:in `register'
        from (irb):6
        from /usr/bin/irb:11:in `<main>'
```

I'm working on the assumption that some dependent gem has lost its mind, but I'll file this here in the hope someone else might know more quickly than I can find out.

### PR DESCRIPTION
**Pull request by nhinds**
`jwt.sign` stopped modifying the JSON::JWT object it is called on in `json-jwt` 1.6.2.
    
Use the returned `JSON::JWS` object directly so that the algorithm is correctly populated.
    
Fixes #74

This is a short-term fix, given the desire to remove the dependency on `json-jwt` entirely in #75, but this should allow `acme-client` to work with the current release of `json-jwt` in the meantime.

### CODE REVIEW

**Comment by unixcharles** [comment]
thanks @nhinds!

**Comment by mpalmer** [comment]
Since presumably this new calling convention won't work on older versions of `json-jwt`, shouldn't there be a version restriction to prevent people using newer `acme-client` against older `json-jwt`?

**Comment by nhinds** [comment]
The `json-jwt` maintainer indicated on https://github.com/nov/json-jwt/issues/39 that this was the intended usage of their library. I had assumed this has always been the intended usage of their library.

Verified as working (i.e. the code for the readme up to `client.register(...)` does not fail) with the following versions of json-jwt:
* 1.6.3
* 1.5.2
* 1.5.0
* 1.4.0
* 1.3.0
* 1.2.3

And `acme-client` currently requires `json-jwt` `>=1.2.3`.

Are you observing a failure with an older version of `json-jwt`, @mpalmer?

My test setup:
```
$ cat Gemfile
# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem 'acme-client', git: 'https://github.com/unixcharles/acme-client.git'

gem 'json-jwt', ENV['JSON_JWT']

$ cat readme.rb 
require 'openssl'
private_key = OpenSSL::PKey::RSA.new(4096)

endpoint = 'https://acme-staging.api.letsencrypt.org/'

# Initialize the client
require 'acme-client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options: { request: { open_timeout: 5, timeout: 5 } })

# If the private key is not known to the server, we need to register it for the first time.
registration = client.register(contact: 'mailto:contact@example.com')
puts "Successful on #{ENV['JSON_JWT']}"
```

**Comment by unixcharles** [comment]
My understanding is that I was just using the API wrong. Let me know if it cause any problems to any of you so we can adjust before releasing a new gem version.

**Comment by schmurfy** [comment]
was a released made ? I am currently trying 0.3.6 but got this error, I tried to lock to json-jwt 1.5.2 but still get it...

**Comment by unixcharles** [comment]
just released 0.3.7 now

**Comment by schmurfy** [comment]
thanks :)

**Pull request merged**
